environment:
  # Убедитесь, что этот диапазон позволяет Dart 3.7 (или выше, если вы уверены в GH Actions)
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flet: ^0.10.0 
  
  # КЛЮЧЕВОЕ ИСПРАВЛЕНИЕ: Принудительное понижение версии webview
  webview_flutter: 4.0.5 